### ISSUE TITLE
O site do anitube mudou, então ocorre um erro de URL

### ISSUE THREAD

**Issue by allan694** [andre-alves/AniTubeDownloaderPRO#1]
O site atual é http://www.anitube.se/
não mais o http://anitube.xpg.uol.com.br

HTTP error fetching URL
HTTP error fetching URL
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=503, URL=http://anitube.xpg.uol.com.br/search/1/?sort=&search_type=videos&search_id=naruto&search_key=
	at org.jsoup.helper.HttpConnection$Response.execute(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.<unknown>(Unknown Source)
	at org.jsoup.helper.HttpConnection.execute(Unknown Source)
	at org.jsoup.helper.HttpConnection.get(Unknown Source)
	at anitube.downloader.crawler.CrawlerPesquisa.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by andre-alves** [comment]
Testei aqui e ainda está funcionando o http://anitube.xpg.uol.com.br.

O http://www.anitube.se/ sempre existiu na verdade, é que antes ele redirecionava pro xpg.

Pode ser que o meu DNS não tenha atualizado ainda, vou tentar novamente amanhã.

Obrigado.

**Comment by andre-alves** [comment]
Testei durante a semana e aqui funcionou normalmente.

Talvez tenha sido algo temporário.

Vou fechar esse issue, qualquer coisa você ainda pode comentar sobre o problema.

**Comment by allan694** [comment]
Olá de novo, me desculpe por não responder.

Mas agora há um novo problema, como o AniTube agora é bloqueado fora do Japão, você poderia atualizar o link para o AniTube! Brasil, http://www.anitube.info/ ?

**Comment by kaduuchiha** [comment]
melhor ainda pessoal, www.anitube.me
